[supervisord]
nodaemon=false
logfile=/dev/null
pidfile=/tmp/supervisord.pid

[program:aria2]
command=aria2c --enable-rpc --rpc-listen-port=6800 --dir=/cloudreve/data/temp/aria2 --input-file=/cloudreve/data/temp/aria2/aria2.session --save-session=/cloudreve/data/temp/aria2/aria2.session --listen-port=6888 --dht-listen-port=6888
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
