services:
    caddy:
        image: nginx:alpine
        ports:
            - 80:80
            - 443:443
        volumes:
            - /dockercnf/nginx/conf.d:/etc/nginx/conf.d
            - /dockercnf/nginx/ssl:/etc/nginx/ssl
        networks:
            - cloudreve-network
        restart: unless-stopped

    cloudreve:
        image: vedla/cloudreve
        ports:
            - 6888:6888
            - 6888:6888/udp
        volumes:
            - ${CLOUDREVE_DATA_PATH}:/cloudreve/data
        networks:
            - cloudreve-network
        restart: unless-stopped


networks:
    cloudreve-network:
