name: Sync Readme

on:
  push:
    branches:
      - master

jobs:
  sync-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        
      - name: Sync README.md
        uses: peter-evans/dockerhub-description@v5
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: ${{ secrets.DOCKERHUB_USERNAME }}/cloudreve
          short-description: ${{ github.event.repository.description }}
          enable-url-completion: true

